"mov	bx,	0	\n\t"
"mov	dx,	1	\n\t"
"and	eax,	255	\n\t"	
".begin:		\n\t"
"cmp	bx,	ax	\n\t"
"je	.end		\n\t"
"push	ax		\n\t"
"mul	dx	   	\n\t"
"mov	dx,	ax	\n\t"
"pop	ax		\n\t"
"dec	ax		\n\t"
"jmp	.begin		\n\t"
".end:			\n\t"
